language: node_js
sudo: false
node_js:
- '4.1'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g grunt-cli karma bower
- npm install
- bower install
script: gulp travis
before_deploy:
- gulp build
deploy:
  provider: npm
  email: outsideris@gmail.com
  api_key:
    secure: KuxrTSTdHMJl4Ma987odsgY4YRe/4u1eLsjCcnUvvBR6Jcmw3lWwZ0NmcGMyb5vYiYMrpa0+BfjmKx+EaUSrLGZGRZjgi1fI19sA6oFncHFHatcCzIfsuxFKOJeQpyNfm2LGVGLe6Tgs/AN/eKqy8cRowewgyi2JAYYbPlCLyEs=
  on:
    tags: true
    repo: summernote/angular-summernote
